[tool.poetry]
name = "backend"
version = "0.1.0"
description = "QuantumOrb project backend"
authors = ["cashblxxd <cashblxxd@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
CacheControl = "^0.14.0"
keyring = "^24.3.0"
packaging = "^23.2"
pre-commit = "^3.6.2"
python-dotenv = "^1.0.1"
pydantic-settings = "^2.2.0"
Django = "^5.0.2"
djangorestframework = "^3.14.0"
setuptools = "^69.1.0"
django-cors-headers = "^4.3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
