type Initialized @entity(immutable: true) {
  id: Bytes!
  version: BigInt! # uint64
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type UserInitialized @entity(immutable: true) {
  id: Bytes!
  user: Bytes! # address
  parent: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type UserUpdated @entity(immutable: true) {
  id: Bytes!
  user: Bytes! # address
  points: BigInt! # uint256
  referralPoints: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type UserXLinked @entity(immutable: true) {
  id: Bytes!
  user: Bytes! # address
  x_link: String! # string
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}
type OrbOpened @entity(immutable: true) {
  id: Bytes!
  user: Bytes! # address
  pointsEarned: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}
type User @entity {
  id: ID!
  points: BigInt!
}
