# Generated by Django 5.2.17 on 2024-01-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexerState',
            fields=[
                ('singleton_id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_processed_block', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('address', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('points', models.BigIntegerField(default=0)),
                ('referral_points', models.BigIntegerField(default=0)),
                ('is_partner', models.BooleanField(default=False)),
                ('last_daily_open', models.BigIntegerField(default=0)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='leaderboard.player')),
            ],
        ),
        migrations.CreateModel(
            name='PendingOrb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orb_type', models.IntegerField(choices=[(0, 'Daily'), (1, 'Genesis'), (2, 'Quantum')])),
                ('commit_block', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending', to='leaderboard.player')),
            ],
        ),
        migrations.CreateModel(
            name='OrbOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=66)),
                ('log_index', models.IntegerField()),
                ('orb_type', models.IntegerField(choices=[(0, 'Daily'), (1, 'Genesis'), (2, 'Quantum')])),
                ('rank', models.SmallIntegerField()),
                ('points', models.BigIntegerField()),
                ('block_number', models.BigIntegerField()),
                ('block_timestamp', models.BigIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opens', to='leaderboard.player')),
            ],
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['-points'], name='leaderboard_points_cf755d_idx'),
        ),
        migrations.AddIndex(
            model_name='orbopen',
            index=models.Index(fields=['-block_number'], name='leaderboard_block_n_d10caa_idx'),
        ),
        migrations.AddConstraint(
            model_name='orbopen',
            constraint=models.UniqueConstraint(fields=('tx_hash', 'log_index'), name='unique_log_entry'),
        ),
    ]
