# Generated by Django 5.2.17 on 2024-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbopen',
            name='commit_block',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='daily_streak',
            field=models.IntegerField(default=0),
        ),
    ]
